apiVersion: v1
kind: Secret
metadata:
    name: backup
    namespace: backup
type: Opaque
stringData:
    rclone.conf: ENC[AES256_GCM,data:8+sbr2CBrGx8NxP571YMS44Cd/QesyqFqUsxJiUkSU8KNon5i1uL3CM7IQuF6D1SynJ+ym8si9o8o2yX/O8qSfRSw52rGIn+X62mdI6Fqltcl4jw+GrK63ZbiwJSZMWNoLFYcNOvD3mf9l/3Y8XfrJRLsSs5ASjKsjqiDtQ1BkVZHxNaIPeYoEf5YaSJWBFo8wG+TeQ0+Cdy6HCbK9sgYqxkHgzNsbUfZTPPuLZ/pVpNvbFkHWd8xTJsRHTsaayHc/P2sj0UlfHCXLyWDJQnqa3mW6Y3TFhTz58l5ledo5wAcv7WexqfUw2RtM4qGKFdqw68RWN4CVbpenJk8ElCVbUTFvJPPhWzxMwSuyZwGEbBAA3vuHvcS9Rb2DAStqsbWSP/xA+zXyo0d6JMozdZrA4cbp0HCWQ44oN1hGWxblG1H05NTYpoovN5LlmugsoRbccMv20IyPURbwVJEpJu5bfDTWTjWMvBVE5y1qG+r9nwXinLTtRFsXCWr9a55VcK/uU7Y6ErGOKf3PGuF8sbUPqAYS9ScRjSg8HxS5oFv+zKNaep0i0Dl5n38kauGYcOUT2UTjxCoWOMzmK0ZXH0oU443gnf3kOfOC5d0cGGY6xEyrQR7Rtv5cJ7iVp1BVRihpKeitbs2+6sD24ZqdS7lUNYIkhb+T5a055h4hB9TrDeQGJ27WiwgKRW5RdLVrqKnBA5w6DD1soEj5aJJwEFpmweN3JKJC0ip0/7HoWVgeWHo3qHKVelF2b0,iv:UOsr8+Nw9HaUwrbxsbgmxvCmsZEzac66s/kTtjdlL0o=,tag:CPxrwIAdZXv8ldZ/NOTcJg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Qq3veldHcSVitAca6DBLcDIiy0ML+lTnBgp55OKUXpn7fmMnzAEErT0A/y8QeM7cjdb2izJJF/GFRQSu1w1pdK4wa8hfh7ny,iv:D6B1ntFGJ++fNFI5w0TA79p8Yp50MG+yC4VCuPxbvHc=,tag:DP/Ibk8J4KyKJa8EugHSdw==,type:str]
    RC_USER: ENC[AES256_GCM,data:Gu6gWN2jJw==,iv:JTeSN2lMXq3Llo8wFWA8teV43ES5mxB+AckVDpKymhQ=,tag:DdXxPdMBJiM29Ao65X9JCQ==,type:str]
    RC_PASS: ENC[AES256_GCM,data:mwsl+QsXLD71kHuJ2UTnO3RJFTsMz+e+vDkPNvGbfhhLquq1C4hMPzIe82TTWT+UEXKFdniRihRtKBVU/JWsGBP9+/EpKmA=,iv:FwNqLqtRo6APiwTxaX9PIpw6z1B4EIaMHsAveMYDKrs=,tag:QbdZp1tR/HimmE4FgIIhmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RmMyQzJ3Sjl1R3RGdm5W
            NktoZlNBRnBTelcrZ2I3d3JFUkNOcnFLRkE4Cm1aOVBIdnhkNEE5Y2JYUzhoZ2dW
            QUEwSnZsL3V0ai9FUGN2bXl1UkNnZUUKLS0tIHVFb1Nvdm5PMVVDanJuWGxVNks0
            bHdPR1ZCNkRmYTZNNFlBTWNLTlhGdUEKtx3yn/KpMMI9/3ii/v5SUWrtK3UAomTv
            JwmfCj/qGK51H+INVdng7046HKXDKjdJVJPBa95WosJygnWVilQnug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8tckzykcehegmqafnhptdlakk0wa4vsqp9jyv6qcameuys4t4kqvegl87
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T16:29:09Z"
    mac: ENC[AES256_GCM,data:NSEloVVpYJ7FBwf77rId5sZu2WSw23Hf2Mf22MseXqE9KJlnszxSG9atNgPW42BXkfEbLDYZ9Cest5yvrhAjBN7A7Yid9p2OyK+8btZWeFdJY011iYDMBlFpSUqHFIGRGpqti7esqwnpFR1jO8qhWdBgBszg9URYyYyqfcCLbng=,iv:VOdAuKFMzGTeD0j1OGpcYiSIJBf34bPTnT5nq5Bq2XU=,tag:djLorxHPVXXMKMgmIu+/GQ==,type:str]
    version: 3.13.3
