apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: observability
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:vjUcCxw=,iv:TPBo4+RTiMrJsWUUu/9akCetLW8bxuTGGpxckb+e+Gs=,tag:1ey9VBa1rIHZWC1lPwTdcw==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:8W5d7hroe6a7ILqs3xXY2R0uz1npjTyNyrPqKzxX3rVCBTQY00uTmQw=,iv:eWaEz/9t6O6pZNjO6sf4eB6LdJB2JzC/ZYpeT68iXy0=,tag:LakbnnEXiq75WNvKoNbBPA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dFF0M2xBL0xlVERZWVlj
            Q3d2TDlvNXlDR2hPem1JVnIzUXBnYkkwaVhNCnR3d1hIdm5yYnVleFN1TVhROE9s
            SVFVcXg3ckZTL0dKVVRRMUlzL3RkOUUKLS0tIE5Ka2J2bm5QV2R5TWh3RzdZL1Vh
            dmJsRXM3OXNVV3FZaFU0STJYQUVYbFkKs4FsQGJUjKmgVNmwL0qB/5PhBsBZfwzT
            aMXuUl0SR899C6olQgnBg1huzyNiak/Qn7dEHWWA7PvCwVIj43Ln7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8tckzykcehegmqafnhptdlakk0wa4vsqp9jyv6qcameuys4t4kqvegl87
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T19:00:17Z"
    mac: ENC[AES256_GCM,data:hUpA82Bxuv1tlC3FaIMA/3gxBMrcWvHuoSzdJ6uRx5horoN1xDBOhssNKAYBY/YCGUn8zHIYDqsktPKvirW+3x/x9YGXwqNMohiHY5ETC+7uFRnSiK6tHZWG9r9xopqscgv4WKvC4G5R7s3LQ4Zut4MX1xXXlThTNaVOTg/3kQQ=,iv:nsbQ9j0cADjZt7/2avV11f7d+QyuH45Uw066HZ9zQsA=,tag:eRGJEZg9rp0vULyE+/GEPg==,type:str]
    version: 3.13.3
