apiVersion: v1
kind: Secret
metadata:
    name: matrix-receiver
    namespace: observability
type: Opaque
stringData:
    MATRIX_USER_ID: ENC[AES256_GCM,data:BjbGuRVXmfK9w+H1cCeG2gXJ4nd0y84ZJmZT8QY=,iv:OAaGq2xsfRVZFCN/CNAtFlHD9pa7gOLiNHXC0kOAjzI=,tag:L2EgSCr4IBpBoOvjX2vl6g==,type:str]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:jUC+Ah4SlqSsGZT1j5Zwdf1GUnOMYUrzyeqICbrnsVXJzuMDbdrReS0=,iv:A1zz4pwMKgl0KwaBqRuHnRRmsPlWRcQ8BH/Zms5ZJ5g=,tag:oUGorpmlA5B3N/iyfh4sVQ==,type:str]
    MATRIX_ROOM_ID: ENC[AES256_GCM,data:fgcR00zpuW1znACbfOneGJGxt1zBp7z2mHmocZXe,iv:YUP0cKPDQn4Ycu8ppLoQE0oyZGLwE7bgqxeT/B0FIXY=,tag:a8aNcIpqW2R1ixC1gk4DKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aFR4YnpMM2pjK3MxN2NC
            WFNqcmFBaVhsRzlYNitwOGt1bEpLLzcxVTBZCmZWSjQxSzdMVU0xMitkUDZTVTd5
            QUU0a0Vkcmg1ekxoTTZmdlY5VXVBQTQKLS0tIEc1bEo2WmtKZTl2OFZtamhtcWtC
            L2NzUy9MbVdWMGpiWkdaOHVzNUptVWMKtUw/VcmHZPM3TLWlLGShR5qYQxf4T/Pi
            qOOOq2Rtl8BPvWvm04tWgbeJRXqJjfGoG6D6aPmum+VMVuU12/SXTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8tckzykcehegmqafnhptdlakk0wa4vsqp9jyv6qcameuys4t4kqvegl87
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T09:20:09Z"
    mac: ENC[AES256_GCM,data:Tr199kcDtgjj1SjzE+CNHlEr1/gqD/AGGUtH65j//NZLhLK3x/aMPkG2D+BjgZP4WjZU+Q8Q+rOJ6FSBshy3FJP7/9UEcizIhr7GipMbmpC7f732BpWpfLuEaCsEG1EZb1CSu1QkmlVg7ZGE7lxMZzq8hT3j//BJTnd/EtnDEmQ=,iv:cc83+kvC8kYXTCDROOxn+r2xL8aJDmV0bkz4QBh4EfA=,tag:AsJAotEONpraADA/SuAy4w==,type:str]
    version: 3.13.3
