apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repositories
  - kube-prometheus-stack
  - loki
  - alloy
  - device-metrics-exporter
  - matrix-receiver
