apiVersion: v1
kind: Secret
metadata:
    name: matrix-notifier
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Ss8cp0gwVJ2WGhaDJhu+9t90O6jYKT+w7MpPt82RmMn1bsmYUvDQ394=,iv:9FM64XneYZiTWw5OqnA8KSDzKJ/wY2GJtL+FcOwEM1Y=,tag:y12uv4eenyVUjzuZdLZ9ug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRnIrZmdobDZNSEt4VzZj
            N1lzeTV0YjF3SGE2ckZIZlVCcFovbmRoTW1nCmdjOVNJU2Z1dHhCcXNyNVlETFo1
            akQvODNnajZJcjVreVVKdEc5L1d5d3cKLS0tIEcxZHB0L3dFeXlVZzhRWW41eE5o
            M2QvblhUcTVWUDJaNHJ6SHh2YlJpZVUKkj7CWhkY+4b3uHqExmMejlWPgO63BZoN
            YY8Yk6FSIEXLyH8yC5zJD2QZO4pmGrpXm/GFyxiVrNpCFqVZhibacQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8tckzykcehegmqafnhptdlakk0wa4vsqp9jyv6qcameuys4t4kqvegl87
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T19:49:20Z"
    mac: ENC[AES256_GCM,data:Uo3TB8NoiiRnB6zQcUO52LQd/yutjioYlkHYeE6+Xo9g9WjsiqO4dl0UQkh7mTvz5kgbWurLlMljo2YuG7q9xLx/MH8mmaOEQBCNQSnTiizQyY5EdskqclDZFFkflvGXf6/ZaTGPrE/5R40XSu1Bb5qgHWsDKBL8PtjECxeFzag=,iv:3P/KlUQ6E+HwSK58iAAwHuoRiiqO8eQM9Wcuy4hWqYA=,tag:wlb+sa+LTG9pp3q6mQbhpg==,type:str]
    version: 3.13.3
