apiVersion: v1
kind: Secret
metadata:
    name: affine
    namespace: affine
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:JHFpyOl7ifKMH6dkTyXvFo1PcP0fpfWwrCNjizCyERpG7M+1djSAl4k0akMoFrQctKdrpCnBtlzmK/GtG1VW2OQpKDQIBMv93MpCZgv6iA0G/qp33sbnOLDK4PxVoE55xwGBlLD1OCa4k2GMxDKi,iv:VWr7HsGXRWk0qYv/ZdEK/v0A6+ZoVhwmKpbcgTq2dDA=,tag:N4cPta2okOgg2IjpVYab1Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:pikDItxujlCMFWZcJ4L8R0hmMUjuKbSTuedvApf78xrI+wvv/Huyzt1aKLRzv+/yEThLE7u7hQYUexawTq6LgDmEulDz,iv:1dq1+UerSGR+P2nW61rncsYd6leSIHGdEQyYkd+LyEk=,tag:0hPZG0PV72pGlRJ6R3tUdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ekxXZEtBeitwTzRjN2FU
            YUJkSXhrZ1hyRHIvQ01CZXJmTHdKTUxrZ0ZrClNHbzV6UUFWeFRvb1loKzMxcXRp
            bW1SZnJlQzMzUnNFY3hCalFjdnZ3SHMKLS0tIDRaN0xHTjk2aFdLa0NxdEZQRENK
            NVEwTkJrWGpOemZoUUFSM0VJZnpCbUEKIyGj+Z7RVAUpEY3KwflQoQmtvHQN95yU
            b+LwPqUiDqjP3j7PxwA1ECt9AEoH0M/XVL+BhL20hatX3uPvQAyFiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8tckzykcehegmqafnhptdlakk0wa4vsqp9jyv6qcameuys4t4kqvegl87
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T22:14:47Z"
    mac: ENC[AES256_GCM,data:10NUWrvYowIZr/uV+8uoLcOPbbSJ+CEm8ucpiywZX3n0x/IiMTcGHzGeV6+ychyxEzHPdet6sYBdgth5NnGWy8wAn29vtc/fBuwUXgn4por7a4FQw1rVPIk8ZGXf2/oV9o9rg7kX3Lthm8gctqG7gnVVxGQA83Kg+Qyzh6PZ4+Q=,iv:OzRU3XRufBFQlWoLF6JeoE8eHM5zNP/bYDw9zJNHw0w=,tag:x44oIdgR7pxIPsocWhDIDg==,type:str]
    version: 3.13.3
