apiVersion: v1
kind: Secret
metadata:
    name: affine
    namespace: affine
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:NH5mwdoqYF7Sbg+mX3B8eOPMpYFIqGKJpRU4pg9LreL6nsosaoZqeqtbd5BIT4TyhagpuJuq5Gs6tIJn6ApIGclDAZlu,iv:lyrU1ZuyX+U7Rpg3e20GV+ZoyhmuCd8agi07VJkJw2o=,tag:UKcPfF83aFCz+KbD8pVDfg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7Z0xMS+xzEJUnyi2OmYFy4dEjjvm9IuCrQKbFL7bysy06s505uRk3L6G39IJ6alQPfw1tlkvIDlgwEGYg74B8HlZvFle6j6XPw9kNQilao7D3yLmbVDFrZbelyTkL2582tq1wgToq81s4mnWtDql,iv:L5XjjpNi996p9bz+906syqfTYczSQW0Bmnmu2mCpv20=,tag:ubFEHrBCcVQnTdqM6LyCMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ekxXZEtBeitwTzRjN2FU
            YUJkSXhrZ1hyRHIvQ01CZXJmTHdKTUxrZ0ZrClNHbzV6UUFWeFRvb1loKzMxcXRp
            bW1SZnJlQzMzUnNFY3hCalFjdnZ3SHMKLS0tIDRaN0xHTjk2aFdLa0NxdEZQRENK
            NVEwTkJrWGpOemZoUUFSM0VJZnpCbUEKIyGj+Z7RVAUpEY3KwflQoQmtvHQN95yU
            b+LwPqUiDqjP3j7PxwA1ECt9AEoH0M/XVL+BhL20hatX3uPvQAyFiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8tckzykcehegmqafnhptdlakk0wa4vsqp9jyv6qcameuys4t4kqvegl87
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T21:55:06Z"
    mac: ENC[AES256_GCM,data:7ZC9okLEHgCwBEHXgfwH1YEoxiZc90KzMReNsYVO+boAYG+G0Qe7Ns57MTcxLlZYLNt0s9MegHaBDcThe3lIwhFbqwrxWKl1857RoQkHnvtOcnf9ZlJVxhxipYEMcdafb6gWbHizUHlEYa32y4tYB7S6VNhtmn9O0Z+VH2NUYyk=,iv:/HF616GlycjdSObyD5o8VhLnfRniFnF9gyXmPLuzUxU=,tag:3S5eBYuFyMs5BlLWGkzQvQ==,type:str]
    version: 3.13.3
