apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
    namespace: nextcloud
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:+PFbju+C/Wrfx6igi4PGsX2+9/EHWoa7MMm/mrWEDyT0IlyXsIo=,iv:bW3rS8T1ozNfKuhQMDROFTb38SCo4nj5R2dvTP7Vsuc=,tag:v0Piui1hLHiO4EOtsJMbMg==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:YfpYpSAxcodbOaNg5dVQEFNlyFjDy7z4PNOLy9RyTvoZ/xW/Jps=,iv:785xP9KyrGx3lOOWAaYJpr6dVdxXu6u0GUHBKYQ60NA=,tag:+0DJHJUY+MjYnouV6mjtcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpS1J1ejY2eWN6UXlhYm1o
            OFBCa3NWcTl2Rk5aZnNJZjNTVmM1Y0VCaGtzCmlLcGVCeUJrVkp6eGEvck9MclBY
            aCtFdUJiSVdMb0JkQXZ5L0o1eXE1cTQKLS0tIDd4bDFXeXNCY2I0OXFOdGNVWDhN
            RlhLMUVXVHVzSkxWMis3aXhZczNHTU0K0RZjIX2ob6dslKLkyiVCXjUMn+OthZG5
            ZzVEsVOxHmZFZx2hfM7yNzl/3yO3yLesxsdjQRK5OUWU1G9LhSqhyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8tckzykcehegmqafnhptdlakk0wa4vsqp9jyv6qcameuys4t4kqvegl87
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T13:59:43Z"
    mac: ENC[AES256_GCM,data:SO8ijDjcp1W5olQjwpwCCVuc/hUcXxmkYjAnOr0Lt9iiYPpC1EsBiAEO0B5bphVTAeTqiKZ/XlpEfUmmp1x805tF6sKJP7VAcWKkeR/8ARFxnkzgW35gzm5pYp2Dljp8L0SO8w42I+710XZTNl49E5ARx67EyGEIdAoJhVmIGPk=,iv:7e4EIUhShKWKXMQWKjBs4AwhV9T3zzw4gNeUhKTlSH0=,tag:4sZA6SlS55xYDaz1t/R53A==,type:str]
    version: 3.13.3
