apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:18.6@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
          env:
            - name: POSTGRES_DB
              value: "keycloak"
            - name: PGDATA
              value: /var/lib/postgresql/data
            - name: POSTGRES_USER
              value: "keycloak"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: DB_PASSWORD
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - keycloak
                - -d
                - keycloak
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.7.3@sha256:ff4257d0d64efbe99ed1ddfaf07765cc3c36dc7518bf8324d41961327f441c54
          args:
            - start
          env:
            - name: KC_HOSTNAME
              value: "https://auth.khazadum.net"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL_HOST
              value: "127.0.0.1"
            - name: KC_DB_URL_DATABASE
              value: "keycloak"
            - name: KC_DB_USERNAME
              value: "keycloak"
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: DB_PASSWORD
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_HEALTH_ENABLED
              value: "true"
          ports:
            - containerPort: 8080
            - containerPort: 9000
          startupProbe:
            httpGet:
              path: /health/ready
              port: 9000
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            periodSeconds: 15
            failureThreshold: 3
      volumes:
        - name: postgres-data
          hostPath:
            path: /data/crypt/keycloak/postgres
            type: DirectoryOrCreate
