apiVersion: v1
kind: Secret
metadata:
    name: keycloak
    namespace: keycloak
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:093OLzNlAU/F5TX8hrKvLfQFX6D6pdpsgfJy/1eWLfVCicq+CGMWS6RrUls7vCaTAqjbmseQ2QTp+Cert3OFECr9FQS3LdUwhgZYo9wR,iv:vOOM2fmJWJvRFaLtO+h9JNZAI5jLWn2fyxPOZHPhIVU=,tag:BPINUj+TPKghGLcU4hU+kA==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:GPx6MyQiEWwMKn5KXL4QYr81e5nc1EzPXfHkt1MgnVoPVClykeKWlfHW0pFV6cXL18SgdOtGK6zs221IjIP7kg==,iv:OVbK2wys4LIZFbyXYBS869fTGjyFf2c7Wrgi90BKagk=,tag:5oH/M4s3GngH/ny6OEj4Sg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZmVtZ292bXMvNVlFKzVX
            VlN3V2s3Wnc4Q2xja3ozWll6alppMzZXY1VRCnZjZXJpSkl1TDkvbzdLc0VMaWlW
            RnpIRS96U1lxYU9tWkJzWjZRYTM2OE0KLS0tIFIzc0lsU0U0aktvZDBzQkFodXJ0
            TzM1aHhCRjRKcDUwVXdielhVMzNwNGcKb8W54Uu1bpvX/wC3t4wMpasAmJj/JRUt
            AKrZqPZ8hmLAG13GkC304hCSDEZxWtl1DhFhfASZDTN3felsEEhLzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8tckzykcehegmqafnhptdlakk0wa4vsqp9jyv6qcameuys4t4kqvegl87
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T20:48:34Z"
    mac: ENC[AES256_GCM,data:Zkcm5SgtP6Cfe4wV2aqEXjCE5dgH+tWamYqIEFuCqA68TFz8my4k5LiB4gAkdginuAUAFIriIh0Uib0B4vFIfJY5Mco6p2N01TBtK6W2vOTDrW5iY6mSv8NeNaALmpkOenZTF7M9aCozIokOCBHJL4TyCKdww206rGkmb9BTRBA=,iv:dL5sllTqLkUpYr0PIheCYuJjODZEA5YOXpZWfd19YJs=,tag:SDGUSzqMpMRZkk8BFIWbPg==,type:str]
    version: 3.13.3
