apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.js: |
    module.exports = {
      platform: 'forgejo',
      endpoint: 'http://git.git.svc.cluster.local:3000/api/v1',
      gitUrl: 'endpoint',
      autodiscover: false,
      repositories: ['ruben/khazadum', 'ruben/gundabad'],
      gitAuthor: 'Renovate Bot <renovate@khazadum.net>',
      timezone: 'Europe/Brussels',
      onboarding: true,
    };
