apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "0 3 * * *"
  timeZone: Europe/Brussels
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: renovate
        spec:
          restartPolicy: Never
          containers:
            - name: renovate
              image: docker.io/renovate/renovate:44.65.0@sha256:2c10dbd2e27cb13978ce8d0ea5db2a858d09d3ed9c7f4759acb796f7feb5fece
              env:
                - name: RENOVATE_CONFIG_FILE
                  value: /opt/renovate/config.js
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate
                      key: RENOVATE_TOKEN
                - name: RENOVATE_GITHUB_COM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate
                      key: RENOVATE_GITHUB_COM_TOKEN
                - name: LOG_LEVEL
                  value: info
              volumeMounts:
                - name: config
                  mountPath: /opt/renovate/config.js
                  subPath: config.js
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: renovate-config
