apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "0 */2 * * *" # every 2h
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: renovate
        spec:
          restartPolicy: Never
          containers:
            - name: renovate
              image: docker.io/renovate/renovate:44.45.1@sha256:1c84139f1f0fe55fed6d8eadd33cdffc9b561078464b29d00e6c25ea6d322cab
              env:
                - name: RENOVATE_CONFIG_FILE
                  value: /opt/renovate/config.js
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate
                      key: RENOVATE_TOKEN
                - name: RENOVATE_GITHUB_COM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate
                      key: RENOVATE_GITHUB_COM_TOKEN
                - name: LOG_LEVEL
                  value: info
              volumeMounts:
                - name: config
                  mountPath: /opt/renovate/config.js
                  subPath: config.js
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: renovate-config
