apiVersion: v1
kind: Secret
metadata:
    name: renovate
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:A1P2oBh5LMY2Xa4pyewZXEFTos6dOG5cyoCQlYURi8mJ4XCGLctIrQ==,iv:OI0waO8AZrcyOh/EPD61y82w1ByoiCymhMmYa3xb3H0=,tag:8A590AGcVjiGoNCN94LVfA==,type:str]
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:GnDe39Z4IdhgPn6BlUyMjPWLptMuJgguxtIxakvEeq1KfBB3VzTboA==,iv:ImAv0pox8n/1ggogqAyRtHGREPsP131iYxnpeAEufGo=,tag:5p0eyTMonPTsa36rLjOOpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaXc3emRKUWNpcUdSeXU2
            NmtqazR0cExBYTI1N3pIOWE4VGgraHRHMm5VCjZtMDZvdklEcGFlYXdaaW1KNklT
            SzdYSVpZaE1Vc09aNU5ON21FOG9WS0EKLS0tIFIyZEtPaEhiTFFoZFJTMCtvVE1I
            dXo0c1puakU1RGFoakVIdnVXcUN2UDAK4RLaYfmq9bouMs873nZ03Nt1P/oxYeix
            ohmE1XoQnJG0R9wDkz4cbLOJluZSfNj6WLlBFh/8PQsIPXAOKu1Phw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8tckzykcehegmqafnhptdlakk0wa4vsqp9jyv6qcameuys4t4kqvegl87
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T19:45:17Z"
    mac: ENC[AES256_GCM,data:vbAEByW6xxTOfwT61XwBMpTxgoVFBVcSnsRmgwbsZTxBV3NAVv9RHemoclxwmEm+8SQOu70PODvzMDO1T3reO1Ox9Xq/g9YhsTfxOsOcm8zkXQ1YaMvkPiHPlJh9OmZ3E6qFDZnOXlhPMOfVfF4fPL1IvdYdPtatC/r0PBayiHw=,iv:dtTC9ISbiU8oZAPIlgq2oqjViKjPrfRNUMMLV8CrOu0=,tag:ok4GXbt242Asj08P+stmQQ==,type:str]
    version: 3.13.3
