apiVersion: v1
kind: Secret
metadata:
    name: renovate
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:A1P2oBh5LMY2Xa4pyewZXEFTos6dOG5cyoCQlYURi8mJ4XCGLctIrQ==,iv:OI0waO8AZrcyOh/EPD61y82w1ByoiCymhMmYa3xb3H0=,tag:8A590AGcVjiGoNCN94LVfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaXc3emRKUWNpcUdSeXU2
            NmtqazR0cExBYTI1N3pIOWE4VGgraHRHMm5VCjZtMDZvdklEcGFlYXdaaW1KNklT
            SzdYSVpZaE1Vc09aNU5ON21FOG9WS0EKLS0tIFIyZEtPaEhiTFFoZFJTMCtvVE1I
            dXo0c1puakU1RGFoakVIdnVXcUN2UDAK4RLaYfmq9bouMs873nZ03Nt1P/oxYeix
            ohmE1XoQnJG0R9wDkz4cbLOJluZSfNj6WLlBFh/8PQsIPXAOKu1Phw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q8tckzykcehegmqafnhptdlakk0wa4vsqp9jyv6qcameuys4t4kqvegl87
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T22:08:15Z"
    mac: ENC[AES256_GCM,data:tKJUaEAOU2aX7RAYWsvwwWeQ7l7F30/waE1w++kzzdJGMtFi76VwS+qlxxcofhHBzKZktAKa+r2xAqOKJDRvFYF7HHRAzZSMSruS36BhVLD5uTjp9RaEufDiFw2Dahnj/4tAJzw2a4SCXlIUIi6Ly10f4FACsYlo1WhsZmyWHps=,iv:RENMSC53rlp+KcUk7pthFjBw0lu9oeKOKEqwM0uuJig=,tag:kEFAld7YNd0cMgryJRTCCQ==,type:str]
    version: 3.13.3
