apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes
  namespace: hermes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
        - name: hermes
          image: docker.io/nousresearch/hermes-agent:latest@sha256:b1ff4b7842d02d422709aa90e02b5ee8209c9d767361edde32165cb188c0cb61
          args: ["gateway", "run"]
          ports:
            - containerPort: 8642
            - containerPort: 9119
          env:
            - name: HERMES_DASHBOARD
              value: "1"
          volumeMounts:
            - name: hermes
              mountPath: /opt/data
      volumes:
        - name: hermes
          hostPath:
            path: /data/crypt/hermes
            type: Directory
