apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes
  namespace: hermes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
        - name: hermes
          image: docker.io/nousresearch/hermes-agent:latest@sha256:c40ad834a51175de77835fc05f087da4f260fa8b58a84e2d1f2b996bfdde54d0
          args: ["gateway", "run"]
          ports:
            - containerPort: 8642
            - containerPort: 9119
          env:
            - name: HERMES_DASHBOARD
              value: "1"
          volumeMounts:
            - name: hermes
              mountPath: /opt/data
      volumes:
        - name: hermes
          hostPath:
            path: /data/crypt/hermes
            type: Directory
