apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes
  namespace: hermes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes
  template:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
        - name: hermes
          image: docker.io/nousresearch/hermes-agent:latest@sha256:9ecae24023ad86cd82f857469562048e251fda045c8b7b726bcb0961e8c63e4f
          args: ["gateway", "run"]
          ports:
            - containerPort: 8642
            - containerPort: 9119
          env:
            - name: HERMES_DASHBOARD
              value: "1"
          volumeMounts:
            - name: hermes
              mountPath: /opt/data
      volumes:
        - name: hermes
          hostPath:
            path: /data/crypt/hermes
            type: Directory
