apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible
  namespace: ansible
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
        - name: ansible
          image: quay.io/ansible/awx-ee:latest@sha256:eaab9b09f731e3561ee0d932123a9971c76095555520f71da7ff4f2d433b4c99
          command: ["sleep", "infinity"]
