apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  url: https://grafana.github.io/helm-charts
  # short interval, otherwise renovate might bump chart version
  # long before flux cache gets refreshed
  interval: 1h
