apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
  namespace: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      containers:
      - name: openwebui
        image: ghcr.io/open-webui/open-webui:main@sha256:8afd2d774834c618a75411b3491cdc5da7396dc464f56a160b937ff2992eb6e4
        ports:
        - containerPort: 8080
        env:
        - name: ENABLE_ADMIN_CHAT_ACCESS
          value: "false"
        volumeMounts:
        - name: openwebui-data
          mountPath: /app/backend/data
      volumes:
      - name: openwebui-data
        hostPath:
          path: /data/crypt/ai/openwebui
          type: Directory
