apiVersion: apps/v1
kind: Deployment
metadata:
  name: git
  namespace: git
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: git
  template:
    metadata:
      labels:
        app: git
    spec:
      containers:
      - name: git
        image: codeberg.org/forgejo/forgejo:16.0.4@sha256:a3e33d03e771d3e58b27de5573c3a25dc4f670583a6724c1878a6d0bbecf3556
        ports:
        - containerPort: 3000
        env:
        - name: FORGEJO__server__DOMAIN
          value: "git.khazadum.net"
        - name: FORGEJO__server__ROOT_URL
          value: "http://git.khazadum.net/"
        - name: FORGEJO__server__START_SSH_SERVER
          value: "false"
        volumeMounts:
        - name: git-data
          mountPath: /data
      volumes:
      - name: git-data
        hostPath:
          path: /data/crypt/git
          type: DirectoryOrCreate
